### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by jsumners** [lasso-js/lasso-marko-taglib#11]
The `page-tag` has a dependency on `raptor-async`:

https://github.com/lasso-js/lasso-marko-taglib/blob/7a6342733f93e4c82ba072af6e1c1fa685a3e864/taglib/page-tag.js#L5

However, that dependency is not listed in `package.json`:

https://github.com/lasso-js/lasso-marko-taglib/blob/7a6342733f93e4c82ba072af6e1c1fa685a3e864/package.json#L41-L45

This means `@lassojs/marko-taglib` does not work when using a package manager that does not create a flat `node_modules` directory, e.g. [pnpm](https://pnpm.js.org).

**Comment by austinkelleher** [comment]
Thanks for pointing this out @jsumners. This is fixed in `@lasso/marko-taglib@1.0.10`.

**Comment by jsumners** [comment]
Thank you.
