### ISSUE TITLE
Missing 'async' dependency causing error

### ISSUE THREAD

**Issue by gunjam** [lasso-js/lasso-marko-taglib#16]
[lasso-resources-root-tag.js](https://github.com/lasso-js/lasso-marko-taglib/blob/master/taglib/lasso-resources-root-tag.js) requires the `async` module, but it's not declared in the `package.json`. This is causing an error to be thrown when I try to run my project.

This package used to work because `async` was a dependency of `lasso`, but it was [recently removed](https://github.com/lasso-js/lasso/commit/7f0e7e76b6e14d9b2d948370ec15486d5e6224fd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) in version 3.2.0.

**Comment by DylanPiercey** [comment]
Sorry this took so long to get too. I don't currently have publish access but the patch for this will be released tomorrow. Thanks for creating the issue 😄.
